apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "communities.fullname" . }}-config
  labels:
    {{- include "communities.labels" . | nindent 4 }}
data:
  routing.yaml: |
    create_server: "{{ .Values.routing.createServer }}"
    delete_server: "{{ .Values.routing.deleteServer }}"
    create_channel: "{{ .Values.routing.createChannel }}"
    delete_channel: "{{ .Values.routing.deleteChannel }}"
    update_channel: "{{ .Values.routing.updateChannel }}"
    user_join_server: "{{ .Values.routing.userJoinServer }}"
    user_leave_server: "{{ .Values.routing.userLeaveServer }}"
    upsert_role: "{{ .Values.routing.upsertRole }}"
    delete_role: "{{ .Values.routing.deleteRole }}"
    member_assign_to_role: "{{ .Values.routing.memberAssignToRole }}"
    member_unassign_from_role: "{{ .Values.routing.memberUnassignFromRole }}"
