{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "communities.fullname" . }}-db
  labels:
    {{- include "communities.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.password }}
  password: {{ .Values.database.password | b64enc | quote }}
  {{- else if .Values.database.autoGeneratePassword }}
  {{- /* Generate a 32-character random alphanumeric password */}}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- else }}
  password: {{ required "database.password is required when database.existingSecret is not set and database.autoGeneratePassword is false" .Values.database.password | b64enc | quote }}
  {{- end }}
{{- end }}
