{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "communities.fullname" . }}-db
  labels:
    {{- include "communities.labels" . | nindent 4 }}
type: Opaque
data:
  # Default password - CHANGE THIS IN PRODUCTION
  # echo -n "password" | base64
  password: cGFzc3dvcmQ=
{{- end }}
