{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "communities.fullname" . }}-db
  labels:
    {{- include "communities.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ required "database.password is required when database.existingSecret is not set" .Values.database.password | b64enc | quote }}
{{- end }}
---
{{- if not .Values.spicedb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "communities.fullname" . }}-spicedb
  labels:
    {{- include "communities.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ required "spicedb.token is required when spicedb.existingSecret is not set" .Values.spicedb.token | b64enc | quote }}
{{- end }}
