# Message Routing Configuration
# This file defines the exchange names and routing keys for outbox events

create_server: "create.server"
delete_server: "delete.server"
create_channel: "create.channel"
delete_channel: "delete.channel"
update_channel: "update.channel"
user_join_server: "user.join.server"
user_leave_server: "user.leave.server"
upsert_role: "role.upsert"
delete_role: "role.delete"
member_assign_to_role: "member.assign.role"
member_unassign_from_role: "member.unassign.role"
