apiVersion: v2
name: communities
description: Communities microservice for managing servers, members, roles, and channels
type: application
version: 0.1.0
appVersion: "0.0.1"
keywords:
  - communities
  - microservice
  - rust
maintainers:
  - name: beep
    email: contact@beep.ovh
